const CATEGORIES = [
  { id: 'bakery',    label: 'Bakery',    icon: '🎂', color: '#D97706', bg: '#FFFBEB' },
  { id: 'florist',   label: 'Florist',   icon: '🌸', color: '#EC4899', bg: '#FDF2F8' },
  { id: 'laundry',   label: 'Laundry',   icon: '👕', color: '#3B82F6', bg: '#EFF6FF' },
  { id: 'guru-les',  label: 'Guru Les',  icon: '📚', color: '#8B5CF6', bg: '#F5F3FF' },
  { id: 'katering',  label: 'Katering',  icon: '🍽️', color: '#EF4444', bg: '#FEF2F2' },
];

const AREAS = [
  { id: 'Jakarta Utara',  label: 'Jakarta Utara',  icon: '🏖️', color: '#0EA5E9', bg: '#F0F9FF' },
  { id: 'Jakarta Selatan', label: 'Jakarta Selatan', icon: '🌳', color: '#16A34A', bg: '#F0FDF4' },
  { id: 'Jakarta Barat',  label: 'Jakarta Barat',  icon: '🏙️', color: '#6366F1', bg: '#EEF2FF' },
  { id: 'Jakarta Timur',  label: 'Jakarta Timur',  icon: '🌅', color: '#EA580C', bg: '#FFF7ED' },
  { id: 'Tangerang',      label: 'Tangerang',      icon: '🏘️', color: '#0D9488', bg: '#F0FDFA' },
];

function getAreaById(id) {
  return AREAS.find(a => a.id === id) || null;
}

const SAMPLE_BUSINESSES = [
  // --- BAKERY ---
  {
    id: 1,
    name: 'Kikki Bakes',
    category: 'bakery',
    description: 'Custom cake & korean cake.',
    address: 'PIK, Jakarta Utara',
    city: 'Jakarta Utara',
    whatsapp: '6281333335129',
    instagram: 'kikkibakes.id',
    photo: null,
    featured: true,
  },
  {
    id: 2,
    name: 'By Sowon',
    category: 'bakery',
    description: 'Korean cake.',
    address: 'Rawamangun, Jakarta Timur',
    city: 'Jakarta Timur',
    whatsapp: '6281399891316',
    instagram: '_by.sowon',
    photo: null,
    featured: false,
  },
  {
    id: 3,
    name: 'Auguri',
    category: 'bakery',
    description: 'Custom cake & entremet.',
    address: 'Pluit, Jakarta Utara',
    city: 'Jakarta Utara',
    whatsapp: '628111342507',
    instagram: 'auguri.id',
    photo: null,
    featured: false,
  },
  {
    id: 4,
    name: 'Wanderbakes',
    category: 'bakery',
    description: 'Custom cake, same day order.',
    address: 'Cengkareng, Jakarta Barat',
    city: 'Jakarta Barat',
    whatsapp: '6281218801119',
    instagram: 'wanderbakes_id',
    photo: null,
    featured: false,
  },
  {
    id: 5,
    name: 'Bake Hour',
    category: 'bakery',
    description: 'Custom cake.',
    address: 'BSD, Tangerang',
    city: 'Tangerang',
    whatsapp: '6285789588881',
    instagram: 'bakehour__',
    photo: null,
    featured: false,
  },
  {
    id: 6,
    name: 'HepiBento',
    category: 'bakery',
    description: 'Custom cake & bento cake.',
    address: 'Kebayoran Lama, Jakarta Selatan',
    city: 'Jakarta Selatan',
    whatsapp: '628176756567',
    instagram: 'hepibento',
    photo: null,
    featured: false,
  },
  {
    id: 7,
    name: 'Yumiru',
    category: 'bakery',
    description: 'Birthday cake, pie tart, number cake.',
    address: 'Gading Serpong, Tangerang',
    city: 'Tangerang',
    whatsapp: '6287875737844',
    instagram: 'yumiru.id',
    photo: null,
    featured: false,
  },
  {
    id: 8,
    name: 'Rinku Patisserie',
    category: 'bakery',
    description: 'Birthday cake & custom cake.',
    address: 'PIK, Jakarta Utara',
    city: 'Jakarta Utara',
    whatsapp: '6281927121120',
    instagram: 'rinku.patisserie',
    photo: null,
    featured: false,
  },
  {
    id: 9,
    name: 'Bakelove',
    category: 'bakery',
    description: 'Custom cake.',
    address: 'Alam Sutera, Tangerang',
    city: 'Tangerang',
    whatsapp: '6281905624722',
    instagram: 'bakelove.id',
    photo: null,
    featured: false,
  },
  {
    id: 10,
    name: 'Moree Cake Co',
    category: 'bakery',
    description: 'Custom cake, urgent order.',
    address: 'Pluit, Jakarta Utara',
    city: 'Jakarta Utara',
    whatsapp: '6281218194878',
    instagram: 'moreecakeco',
    photo: null,
    featured: false,
  },
  // --- FLORIST ---
  {
    id: 11,
    name: 'Bluemerie',
    category: 'florist',
    description: 'Fresh flowers, dried flowers, wedding flowers.',
    address: 'Pluit, Jakarta Utara',
    city: 'Jakarta Utara',
    whatsapp: '6287872577899',
    instagram: 'blumerie.florist',
    photo: null,
    featured: true,
  },
  {
    id: 12,
    name: 'Florentinefleur',
    category: 'florist',
    description: 'Custom bouquet.',
    address: 'Kembangan, Jakarta Barat',
    city: 'Jakarta Barat',
    whatsapp: '6281286228852',
    instagram: 'florentinefleur.co',
    photo: null,
    featured: false,
  },
  {
    id: 13,
    name: 'Rena the Blossom',
    category: 'florist',
    description: 'Giant bouquet.',
    address: 'Pluit, Jakarta Utara',
    city: 'Jakarta Utara',
    whatsapp: '6285117099112',
    instagram: 'renatheblossom',
    photo: null,
    featured: false,
  },
  {
    id: 14,
    name: 'The Fleuriste',
    category: 'florist',
    description: 'Custom bouquet.',
    address: 'Kembangan, Jakarta Barat',
    city: 'Jakarta Barat',
    whatsapp: '6287777600988',
    instagram: 'thefleuristeofficial',
    photo: null,
    featured: false,
  },
  {
    id: 15,
    name: 'Rosy Posy',
    category: 'florist',
    description: 'Fresh flowers, dried flowers.',
    address: 'Palmerah, Jakarta Barat',
    city: 'Jakarta Barat',
    whatsapp: '6281299218885',
    instagram: 'rosyposy.florist',
    photo: null,
    featured: false,
  },
  {
    id: 16,
    name: 'KIKUKO Florist Artistry',
    category: 'florist',
    description: 'Same day bouquet.',
    address: 'Joglo, Jakarta Barat',
    city: 'Jakarta Barat',
    whatsapp: '6282112111120',
    instagram: 'kikukoflorist',
    photo: null,
    featured: false,
  },
  {
    id: 17,
    name: 'Bluerette',
    category: 'florist',
    description: 'Urgent flower order.',
    address: 'Tanjung Duren, Jakarta Barat',
    city: 'Jakarta Barat',
    whatsapp: '6287782666447',
    instagram: 'bluretteflorist',
    photo: null,
    featured: false,
  },
  {
    id: 18,
    name: 'Reverose',
    category: 'florist',
    description: 'Urgent order.',
    address: 'Greenlake, Tangerang',
    city: 'Tangerang',
    whatsapp: '6285158671911',
    instagram: 'reverose.florist',
    photo: null,
    featured: false,
  },
  {
    id: 19,
    name: 'White Lily Florist',
    category: 'florist',
    description: 'Flower bouquet, vase, flower box, wedding.',
    address: 'Lebak Bulus, Jakarta Selatan',
    city: 'Jakarta Selatan',
    whatsapp: '62818102424',
    instagram: 'whitelily.florist',
    photo: null,
    featured: false,
  },
  {
    id: 20,
    name: 'Phane',
    category: 'florist',
    description: 'Urgent order.',
    address: 'Kuningan, Jakarta Selatan',
    city: 'Jakarta Selatan',
    whatsapp: '6287871972868',
    instagram: 'phaneflorist',
    photo: null,
    featured: false,
  },
];

// Merge with user-submitted businesses from localStorage
function getAllBusinesses() {
  const stored = JSON.parse(localStorage.getItem('temuin_businesses') || '[]');
  return [...SAMPLE_BUSINESSES, ...stored];
}

function saveBusinesses(businesses) {
  localStorage.setItem('temuin_businesses', JSON.stringify(businesses));
}

function getCategoryById(id) {
  return CATEGORIES.find(c => c.id === id) || null;
}
